export const currencyList = [
  { symbol: "€", label: "Euro ", code: "EUR" },
  { symbol: "$", label: "United States Dollar", code: "USD" },
  { symbol: "₴", label: "Ukrainian hryvnia", code: "UAH" },
  { symbol: "$", label: "Canadian Dollar", code: "CAD" },
  { symbol: "$", label: "Australian Dollar", code: "AUD" },
  { symbol: "¥", label: "Chinese Yuan", code: "CNY" },
  { symbol: "R$", label: "Brazilian Real", code: "BRL" },
  { symbol: "£", label: "British Pound", code: "GBP" },
  { symbol: ".د.ب", label: "Bahrain Dinar ", code: "BHD" },
  { symbol: "$", label: "Chilean Peso ", code: "CLP" },
  { symbol: "Kč", label: "Czech Republic Koruna ", code: "CZK" },
  { symbol: "kr", label: "Danish Krone ", code: "DKK" },
  { symbol: "$", label: "Hong Kong Dollar ", code: "HKD" },
  { symbol: "Ft", label: "Hungarian Forint ", code: "HUF" },
  { symbol: "₹", label: "Indian Rupee ", code: "INR" },
  { symbol: "₪", label: "Israeli Shekel ", code: "ILS" },
  { symbol: "¥", label: "Japanese Yen ", code: "JPY" },
  { symbol: "د.ا", label: "Jordanian Dinar", code: "JOD" },
  { symbol: "Sh", label: "Kenyan Shilling ", code: "KES" },
  { symbol: "₩", label: "Korean Won ", code: "KRW" },
  { symbol: "د.ك", label: "Kuwaiti Dinar ", code: "KWD" },
  { symbol: "$", label: "Mexican Peso ", code: "MXN" },
  { symbol: "د.م.", label: "Moroccan Dirham ", code: "MAD" },
  { symbol: "$", label: "Namibian Dollar ", code: "NAD" },
  { symbol: "$", label: "New Zealand Dollar ", code: "NZD" },
  { symbol: "kr", label: "Norwegian Krone ", code: "NOK" },
  { symbol: "ر.ع.", label: "Omani Rial ", code: "OMR" },
  { symbol: "zł", label: "Polish Zloty ", code: "PLN" },
  { symbol: "ر.ق", label: "Qatari Rial ", code: "QAR" },
  { symbol: "lei", label: "Romanian Leu ", code: "RON" },
  { symbol: "₽", label: "Russian Ruble ", code: "RUB" },
  { symbol: "﷼", label: "Saudi Riyal ", code: "SAR" },
  { symbol: "$", label: "Singapore Dollar ", code: "SGD" },
  { symbol: "R", label: "South African Rand ", code: "ZAR" },
  { symbol: "kr", label: "Swedish Krona ", code: "SEK" },
  { symbol: "Fr.", label: "Swiss Franc ", code: "CHF" },
  { symbol: "₣", label: "Tahitian (Central Polynesian) Franc ", code: "XPF" },
  { symbol: "฿", label: "Thai Baht ", code: "THB" },
  { symbol: "د.ت", label: "Tunisian Dinar ", code: "TND" },
  { symbol: "₺", label: "Turkish Lira ", code: "TRY" },
  { symbol: "د.إ", label: "United Arab Emirates Dirham ", code: "AED" },
];
